name: Auto ingest from fpl API wh

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'  # Runs at midnight every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python src/components/data_ingestion.py

    - name: Commit files
      run: |
        git config --local user.email "abeech123@virginmedia.com"
        git config --local user.name "AnthonyBeech"
        git add .
        git commit -m "Automated ingestion"
        git push -u origin master
